"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase-browser";
type Station="kitchen"|"bar";
type StationMetric={station:Station;served:number;delayed:number;avg_wait_seconds:number;avg_prep_seconds:number;avg_total_seconds:number;sla_percent:number};
type ProductMetric={product_id:string;product_name:string;station:Station;quantity:number;tickets:number;delayed_tickets:number;avg_prep_seconds:number;avg_total_seconds:number};
type HourMetric={hour:number;served:number;avg_total_seconds:number};
type OperationalStation={station:Station;capacity_units:number;active:number;pending:number;preparing:number;ready:number;queue_work_seconds:number;estimated_wait_seconds:number;pressure_percent:number;capacity_tickets_per_hour:number;predicted_delay_count:number;max_predicted_delay_seconds:number};
type OperationalAlert={id:string;station:Station;severity:"warning"|"critical";title:string;message:string;metric_value:number|null;threshold:number|null;last_triggered_at:string};
type Performance={served:number;delayed:number;avg_wait_seconds:number;avg_prep_seconds:number;avg_total_seconds:number;throughput_per_hour:number;sla_percent:number;stations:StationMetric[];products:ProductMetric[];hours:HourMetric[]};
const empty:Performance={served:0,delayed:0,avg_wait_seconds:0,avg_prep_seconds:0,avg_total_seconds:0,throughput_per_hour:0,sla_percent:0,stations:[],products:[],hours:[]};
const labels:Record<Station,string>={kitchen:"Cozinha",bar:"Bar"};
const duration=(s:number)=>{const n=Math.max(0,Math.round(Number(s||0)));return Math.floor(n/60)+"m "+String(n%60).padStart(2,"0")+"s";};
export default function KDSPerformance(){
 const[business,setBusiness]=useState(""),[role,setRole]=useState(""),[range,setRange]=useState<1|7|30>(7),[data,setData]=useState<Performance>(empty);
 const[control,setControl]=useState<{stations:OperationalStation[];alerts:OperationalAlert[]}>({stations:[],alerts:[]});
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[message,setMessage]=useState("");
 const canConfigure=role==="owner"||role==="manager";
 const loadPerformance=useCallback(async(days=range,target=business)=>{if(!target)return;const to=new Date(),from=new Date(to.getTime()-days*86400000);const{data,error}=await createClient().rpc("get_kds_performance",{p_business_id:target,p_from:from.toISOString(),p_to:to.toISOString()});if(error){setMessage(error.message);return;}setData((data||empty)as Performance);},[business,range]);
 const loadControl=useCallback(async(target=business)=>{if(!target)return;const{data,error}=await createClient().rpc("get_kds_operational_control",{p_business_id:target});if(error){setMessage(error.message);return;}setControl((data||{stations:[],alerts:[]})as{stations:OperationalStation[];alerts:OperationalAlert[]});},[business]);
 useEffect(()=>{async function boot(){const c=createClient(),{data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return;}const{data:m,error}=await c.from("business_memberships").select("business_id,role").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle();if(error||!m){setMessage(error?.message||"Negócio não encontrado");setLoading(false);return;}setBusiness(m.business_id);setRole(m.role);await Promise.all([loadPerformance(range,m.business_id),loadControl(m.business_id)]);setLoading(false);}void boot();},[]);
 useEffect(()=>{if(business)void loadPerformance(range,business);},[business,range,loadPerformance]);
 const peak=useMemo(()=>data.hours.reduce((best,h)=>!best||h.served>best.served?h:best,null as HourMetric|null),[data.hours]);
 const pressure=useMemo(()=>control.stations.reduce((best,s)=>!best||s.pressure_percent>best.pressure_percent?s:best,null as OperationalStation|null),[control.stations]);
 async function saveCapacity(station:Station,value:number){if(!business||!canConfigure)return;const units=Math.max(1,Math.min(20,Math.round(value)));setSaving(station);setMessage("");const{error}=await createClient().rpc("set_production_station_capacity",{p_business_id:business,p_station:station,p_capacity_units:units});if(error)setMessage(error.message);else await loadControl(business);setSaving("");}
 if(loading)return <main className="main"><p>Carregando Central de Performance...</p></main>;
 return <main className="main">
  <div className="topbar"><div><h1 className="title">KDS — Central de Performance</h1><p className="subtitle">Capacidade, pressão de fila, previsão de atraso, SLA e desempenho histórico.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}>{[1,7,30].map(days=><button key={days} type="button" onClick={()=>setRange(days as 1|7|30)} className="btn" style={{width:"auto",background:range===days?"#151515":"#fff",color:range===days?"#fff":"#151515"}}>{days===1?"Hoje":days+" dias"}</button>)}<Link href="/dashboard/kds" className="btn" style={{width:"auto",textDecoration:"none"}}>KDS ao vivo</Link></div></div>
  {message&&<div className="notice">{message}</div>}
  {control.alerts.length>0&&<section className="section"><div className="card"><h2 style={{marginTop:0}}>Alertas ativos</h2><div style={{display:"grid",gap:8}}>{control.alerts.map(a=><div key={a.id} style={{border:"1px solid #ddd",borderLeft:"5px solid #151515",borderRadius:9,padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b>{a.title}</b><span className="label">{a.severity==="critical"?"CRÍTICO":"ATENÇÃO"}</span></div><div className="subtitle" style={{marginTop:4}}>{a.message}</div></div>)}</div></div></section>}
  <div className="grid"><div className="card"><div className="label">SLA de produção</div><div className="value">{data.served?data.sla_percent.toFixed(1):"—"}%</div><div className="subtitle">tickets concluídos dentro do tempo-alvo</div></div><div className="card"><div className="label">Produção/hora</div><div className="value">{data.throughput_per_hour.toFixed(1)}</div><div className="subtitle">{data.served} tickets entregues</div></div><div className="card"><div className="label">Preparo médio</div><div className="value">{duration(data.avg_prep_seconds)}</div><div className="subtitle">início → pronto</div></div><div className="card"><div className="label">Atrasos</div><div className="value">{data.delayed}</div><div className="subtitle">tickets acima do alvo</div></div></div>
  <div className="grid" style={{marginTop:14}}><div className="card"><div className="label">Espera média</div><div className="value">{duration(data.avg_wait_seconds)}</div></div><div className="card"><div className="label">Tempo total médio</div><div className="value">{duration(data.avg_total_seconds)}</div></div><div className="card"><div className="label">Horário de pico</div><div className="value">{peak?String(peak.hour).padStart(2,"0")+":00":"—"}</div><div className="subtitle">{peak?peak.served+" tickets":""}</div></div><div className="card"><div className="label">Maior pressão</div><div className="value">{pressure?pressure.pressure_percent.toFixed(0)+"%":"—"}</div><div className="subtitle">{pressure?labels[pressure.station]+" · espera estimada "+duration(pressure.estimated_wait_seconds):"sem fila ativa"}</div></div></div>
  <section className="section"><div className="card"><h2 style={{marginTop:0}}>Capacidade e pressão por estação</h2><p className="subtitle">Pressão = carga estimada da fila ÷ capacidade configurada. Capacidade/h é uma referência teórica, não uma promessa de atendimento.</p><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12}}>{control.stations.map(s=><div key={s.station} style={{border:"1px solid #ddd",borderRadius:10,padding:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h3 style={{margin:0}}>{labels[s.station]}</h3><b>{s.pressure_percent.toFixed(0)}%</b></div><div className="subtitle">{s.active} ativos · {s.pending} na fila · {s.preparing} preparando · {s.ready} prontos</div><div className="subtitle">Espera estimada {duration(s.estimated_wait_seconds)} · {s.capacity_tickets_per_hour.toFixed(1)} tickets/h</div><div className="subtitle">{s.predicted_delay_count>0?"Atraso previsto em "+s.predicted_delay_count+" ticket(s) · máx. "+duration(s.max_predicted_delay_seconds):"Sem atraso previsto"}</div><div style={{display:"flex",alignItems:"center",gap:8,marginTop:10}}><span className="label">Slots</span><input aria-label={"Slots "+labels[s.station]} type="number" min={1} max={20} defaultValue={s.capacity_units} disabled={!canConfigure||saving===s.station} onChange={e=>{const v=Number(e.target.value);if(v>=1&&v<=20)void saveCapacity(s.station,v)}} style={{width:75,padding:7,border:"1px solid #ddd",borderRadius:7}}/><span className="subtitle">{canConfigure?"salvamento automático":"somente owner/manager"}</span></div></div>)}</div></div></section>
  <section className="section"><div className="card"><h2 style={{marginTop:0}}>Desempenho histórico por estação</h2><div className="table-wrap" style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Estação</th><th>Entregues</th><th>Atrasos</th><th>SLA</th><th>Espera</th><th>Preparo</th><th>Total</th></tr></thead><tbody>{data.stations.map(s=><tr key={s.station}><td><b>{labels[s.station]}</b></td><td>{s.served}</td><td>{s.delayed}</td><td>{s.sla_percent.toFixed(1)}%</td><td>{duration(s.avg_wait_seconds)}</td><td>{duration(s.avg_prep_seconds)}</td><td>{duration(s.avg_total_seconds)}</td></tr>)}{!data.stations.length&&<tr><td colSpan={7}>Ainda não há histórico no período.</td></tr>}</tbody></table></div></div></section>
  <section className="section"><div className="card"><h2 style={{marginTop:0}}>Produtos que exigem atenção</h2><p className="subtitle">Ordenados por atrasos e tempo médio de preparo.</p><div className="table-wrap" style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Produto</th><th>Estação</th><th>Qtd.</th><th>Tickets</th><th>Atrasos</th><th>Preparo médio</th><th>Total médio</th></tr></thead><tbody>{data.products.map(p=><tr key={p.product_id}><td><b>{p.product_name}</b></td><td>{labels[p.station]}</td><td>{Number(p.quantity).toFixed(0)}</td><td>{p.tickets}</td><td>{p.delayed_tickets}</td><td>{duration(p.avg_prep_seconds)}</td><td>{duration(p.avg_total_seconds)}</td></tr>)}{!data.products.length&&<tr><td colSpan={7}>Ainda não há produtos concluídos no período.</td></tr>}</tbody></table></div></div></section>
  <section className="section"><div className="card"><h2 style={{marginTop:0}}>Mapa de demanda por hora</h2><div style={{display:"grid",gridTemplateColumns:"repeat(12,minmax(42px,1fr))",gap:6,overflowX:"auto"}}>{data.hours.map(h=><div key={h.hour} style={{border:"1px solid #ddd",borderRadius:8,padding:8,textAlign:"center",minWidth:42}}><div className="label">{String(h.hour).padStart(2,"0")}h</div><b>{h.served}</b><div className="subtitle">{duration(h.avg_total_seconds)}</div></div>)}</div></div></section>
 </main>;
}
