"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase-browser";
export default function Dashboard(){
 const [email,setEmail]=useState(""),[loading,setLoading]=useState(true),[metrics,setMetrics]=useState<any>(null);
 useEffect(()=>{async function load(){const c=createClient();const {data:{user}}=await c.auth.getUser();setEmail(user?.email??"");const {data:m}=await c.from("business_memberships").select("business_id").eq("user_id",user?.id).eq("active",true).limit(1).maybeSingle();if(m){const {data:d}=await c.from("business_dashboard").select("*").eq("business_id",m.business_id).maybeSingle();setMetrics(d)}setLoading(false)}load()},[]);
 if(loading)return <main className="main"><p>Carregando...</p></main>;
 const revenue=Number(metrics?.revenue||0),cogs=Number(metrics?.cogs||0),gross=revenue-cogs;
 const links=[["Dashboard","/dashboard"],["Vendas / POS","/dashboard/pos"],["Caixa","/dashboard/caixa"],["Estoque","/dashboard/estoque"],["Compras","#"],["Despesas","#"],["Relatórios","#"],["Clientes","#"],["Funcionários","#"],["Configurações","#"]];
 return <div className="shell"><aside className="sidebar"><div className="brand">URBANA <span>CAFÉ</span></div><nav className="nav">{links.map(([label,href])=><Link className={label==="Dashboard"?"active":""} key={label} href={href}>{label}</Link>)}</nav></aside><main className="main"><div className="topbar"><div><h1 className="title">Dashboard</h1><div className="subtitle">Visão geral da operação</div></div><div>{email}</div></div><div className="grid">{[["Faturamento","UYU "+revenue.toFixed(2)],["CMV","UYU "+cogs.toFixed(2)],["Lucro bruto","UYU "+gross.toFixed(2)],["Vendas",String(metrics?.sales_count||0)]].map(([label,value])=><div className="card" key={label}><div className="label">{label}</div><div className="value">{value}</div></div>)}</div><div className="section"><h2>Operação</h2><table className="table"><thead><tr><th>Módulo</th><th>Status</th><th>Ação</th></tr></thead><tbody><tr><td>POS</td><td>Operacional</td><td><Link href="/dashboard/pos">Abrir vendas</Link></td></tr><tr><td>Caixa</td><td>Operacional</td><td><Link href="/dashboard/caixa">Gerenciar caixa</Link></td></tr><tr><td>Estoque</td><td>Operacional</td><td><Link href="/dashboard/estoque">Consultar estoque</Link></td></tr></tbody></table></div></main></div>
}